<script lang="ts">
  // Marketing history — "what did I post, where, and when".
  //
  // Moved off the Dev Console overview (ConsoleOverview.svelte), where it was a
  // bare per-day bar chart deliberately pinned to the Site Traffic date axis for
  // correlation. That coupling is gone: here the panel owns its own window and
  // answers the question the owner actually asks — the specifics. Three views on
  // one dataset:
  //   1. WHEN     — per-day stacked bars, automated (Postiz) vs manual.
  //   2. WHERE    — per-channel totals + how stale each channel is.
  //   3. WHAT     — a reverse-chronological log with subreddit / note detail.
  //
  // Source: src/data/marketing-posts.json. Hybrid — source="postiz" rows are
  // regenerated by `npm run sync:marketing`; source="manual" rows are hand-logged
  // (X / Reddit / TikTok / Patreon) and preserved across syncs.
  import marketingPosts from "../data/marketing-posts.json";

  type Post = {
    date: string;
    platform: string;
    source: string;
    subreddit?: string;
    note?: string;
  };

  // Two series only, so a 2-colour categorical split is the whole palette.
  // Validated against the #0d1320 panel surface: CVD ΔE 27.7 (protan) /
  // 18.3 (tritan) and contrast ≥ 3:1 both pass. They sit just above the
  // dark-mode lightness band, which is the console's existing house
  // brightness (cf. var(--crimson) / #60a5fa in the traffic charts) — identity is
  // never colour-alone here anyway: every series is legended, direct-labelled
  // on the channel bars, and spelled out in the log.
  const COLOR_AUTO = "#a78bfa";
  const COLOR_MANUAL = "#fb923c";

  /** How far back the chart looks. Stated in the UI — don't change silently. */
  const WINDOW_DAYS = 60;

  const posts: Post[] = ((marketingPosts?.posts ?? []) as Post[]).filter((p) => p?.date);

  const DAY_MS = 86_400_000;
  const iso = (t: number) => new Date(t).toISOString().slice(0, 10);
  const parse = (d: string) => Date.parse(`${d}T00:00:00Z`);

  // ---- 1. WHEN: per-day buckets over the trailing window -------------------
  type Day = { date: string; automated: number; manual: number; total: number; platforms: string[] };

  const todayMs = Math.floor(Date.now() / DAY_MS) * DAY_MS;
  const days: Day[] = (() => {
    const byDate: Record<string, Day> = {};
    const out: Day[] = [];
    for (let i = WINDOW_DAYS - 1; i >= 0; i--) {
      const d: Day = { date: iso(todayMs - i * DAY_MS), automated: 0, manual: 0, total: 0, platforms: [] };
      byDate[d.date] = d;
      out.push(d);
    }
    for (const p of posts) {
      const d = byDate[p.date];
      if (!d) continue;
      d.total++;
      if (p.source === "manual") d.manual++;
      else d.automated++;
      const tag = p.source === "manual" ? `${p.platform} (manual)` : p.platform;
      if (!d.platforms.includes(tag)) d.platforms.push(tag);
    }
    return out;
  })();

  const windowStart = days[0]?.date ?? "";
  const windowEnd = days[days.length - 1]?.date ?? "";
  const inWindow = days.reduce((s, d) => s + d.total, 0);
  const maxDay = Math.max(...days.map((d) => d.total), 1);

  // Chart geometry. Single fixed viewBox, scaled by CSS — no JS resize needed.
  const VB_W = 700;
  const PLOT_L = 34;
  const PLOT_R = 8;
  const PLOT_TOP = 12;
  const PLOT_BOT = 118; // baseline y
  const plotW = VB_W - PLOT_L - PLOT_R;
  const stepX = plotW / days.length;
  const barW = Math.max(2, Math.min(14, stepX * 0.62));
  const scaleY = (PLOT_BOT - PLOT_TOP) / maxDay;
  // ~1 tick per week, anchored to the newest day so the right edge is labelled.
  const labelEvery = 7;

  // y ticks: at most 4, integer counts only (posts are whole things).
  const yTicks = (() => {
    const step = Math.max(1, Math.ceil(maxDay / 4));
    const out: number[] = [];
    for (let v = 0; v <= maxDay; v += step) out.push(v);
    if (out[out.length - 1] !== maxDay) out.push(maxDay);
    return out;
  })();

  const shortDate = (d: string) => `${+d.slice(5, 7)}/${+d.slice(8, 10)}`;

  // ---- 2. WHERE: per-channel totals + staleness ----------------------------
  type Channel = {
    platform: string;
    total: number;
    automated: number;
    manual: number;
    last: string;
    daysAgo: number;
    detail: string[];
  };
  const channels: Channel[] = (() => {
    const m: Record<string, Channel> = {};
    for (const p of posts) {
      const c = (m[p.platform] ??= {
        platform: p.platform,
        total: 0,
        automated: 0,
        manual: 0,
        last: p.date,
        daysAgo: 0,
        detail: [],
      });
      c.total++;
      if (p.source === "manual") c.manual++;
      else c.automated++;
      if (p.date > c.last) c.last = p.date;
      if (p.subreddit && !c.detail.includes(`r/${p.subreddit}`)) c.detail.push(`r/${p.subreddit}`);
    }
    return Object.values(m)
      .map((c) => ({ ...c, daysAgo: Math.round((todayMs - parse(c.last)) / DAY_MS) }))
      .sort((a, b) => b.total - a.total || a.platform.localeCompare(b.platform));
  })();
  const maxChannel = Math.max(...channels.map((c) => c.total), 1);

  // ---- 3. WHAT: reverse-chronological log, grouped by day ------------------
  type LogDay = { date: string; daysAgo: number; entries: Post[] };
  const log: LogDay[] = (() => {
    const m: Record<string, Post[]> = {};
    for (const p of posts) (m[p.date] ??= []).push(p);
    return Object.keys(m)
      .sort((a, b) => b.localeCompare(a))
      .map((date) => ({
        date,
        daysAgo: Math.round((todayMs - parse(date)) / DAY_MS),
        entries: [...m[date]].sort(
          (a, b) => a.source.localeCompare(b.source) || a.platform.localeCompare(b.platform)
        ),
      }));
  })();

  const totalPosts = posts.length;
  const firstPost = posts.reduce((a, p) => (a && a < p.date ? a : p.date), "");
  const lastPost = posts.reduce((a, p) => (a > p.date ? a : p.date), "");
  const manualTotal = posts.filter((p) => p.source === "manual").length;
  const autoTotal = totalPosts - manualTotal;
  const ago = (n: number) => (n === 0 ? "today" : n === 1 ? "1 day ago" : `${n} days ago`);
</script>

<section class="mhp">
  <header class="mhp-head">
    <h2>Marketing History</h2>
    <p class="mhp-sub">
      What went out, to which channel, and when. Automated rows come from Postiz via
      <code>npm run sync:marketing</code>; manual rows (X / Reddit / TikTok / Patreon) are
      hand-logged in <code>src/data/marketing-posts.json</code>.
    </p>
    <div class="mhp-stats">
      <span><strong>{totalPosts}</strong> posts</span>
      <span><strong>{autoTotal}</strong> automated</span>
      <span><strong>{manualTotal}</strong> manual</span>
      <span><strong>{channels.length}</strong> channels</span>
      <span class="muted">{firstPost} → {lastPost}</span>
    </div>
  </header>

  {#if totalPosts === 0}
    <p class="mhp-msg">No marketing posts logged yet.</p>
  {:else}
    <!-- WHEN -->
    <div class="mhp-block">
      <h3 class="block-title">
        Posts per day
        <span class="block-sub"
          >last {WINDOW_DAYS} days · {windowStart} → {windowEnd} · {inWindow} post{inWindow === 1
            ? ""
            : "s"} in window</span
        >
      </h3>
      <div class="chart-wrap">
        <svg viewBox="0 0 {VB_W} 138" class="mhp-svg" role="img"
             aria-label="Marketing posts per day over the last {WINDOW_DAYS} days, split automated versus manual">
          {#each yTicks as t}
            {@const y = PLOT_BOT - t * scaleY}
            <line x1={PLOT_L} x2={VB_W - PLOT_R} y1={y} y2={y}
                  stroke="rgba(148,163,184,0.16)" stroke-width="1" />
            <text x={PLOT_L - 6} y={y + 3} fill="var(--ink-soft)" font-size="9" text-anchor="end">{t}</text>
          {/each}
          {#each days as d, i}
            {@const x = PLOT_L + i * stepX + stepX / 2}
            {@const autoH = d.automated * scaleY}
            {@const manH = d.manual * scaleY}
            {@const tip = d.total > 0
              ? `${d.date} — ${d.total} post${d.total === 1 ? "" : "s"}: ${d.platforms.join(", ")}`
              : `${d.date} — no posts`}
            {#if autoH > 0}
              <rect x={x - barW / 2} y={PLOT_BOT - autoH} width={barW} height={autoH}
                    fill={COLOR_AUTO} rx="2"><title>{tip}</title></rect>
            {/if}
            {#if manH > 0}
              <!-- 2px surface gap between stacked segments so the split reads
                   even when both are one unit tall. -->
              <rect x={x - barW / 2} y={PLOT_BOT - autoH - manH - (autoH > 0 ? 2 : 0)}
                    width={barW} height={manH} fill={COLOR_MANUAL} rx="2"><title>{tip}</title></rect>
            {/if}
            {#if (days.length - 1 - i) % labelEvery === 0}
              <text x={x} y={132} fill="var(--ink-soft)" font-size="9" text-anchor="middle"
                >{shortDate(d.date)}</text
              >
            {/if}
          {/each}
          <line x1={PLOT_L} x2={VB_W - PLOT_R} y1={PLOT_BOT} y2={PLOT_BOT}
                stroke="rgba(148,163,184,0.35)" stroke-width="1" />
        </svg>
      </div>
      <div class="legend">
        <span class="legend-item"><span class="dot" style="background:{COLOR_AUTO}"></span>Automated (Postiz)</span>
        <span class="legend-item"><span class="dot" style="background:{COLOR_MANUAL}"></span>Manual (X / Reddit / TikTok / Patreon)</span>
      </div>
    </div>

    <!-- WHERE -->
    <div class="mhp-block">
      <h3 class="block-title">
        By channel <span class="block-sub">all time · newest-first staleness</span>
      </h3>
      <ul class="chan-list">
        {#each channels as c}
          <li class="chan-row" class:stale={c.daysAgo > 14}>
            <span class="chan-name">{c.platform}</span>
            <span class="chan-bar" title="{c.automated} automated · {c.manual} manual">
              {#if c.automated > 0}
                <span class="seg" style="width:{(c.automated / maxChannel) * 100}%;background:{COLOR_AUTO}"></span>
              {/if}
              {#if c.manual > 0}
                <span class="seg" style="width:{(c.manual / maxChannel) * 100}%;background:{COLOR_MANUAL}"></span>
              {/if}
            </span>
            <span class="chan-n">{c.total}</span>
            <span class="chan-last">
              {ago(c.daysAgo)}{#if c.detail.length}<em class="chan-detail">
                  &nbsp;· {c.detail.join(", ")}</em
                >{/if}
            </span>
          </li>
        {/each}
      </ul>
    </div>

    <!-- WHAT -->
    <div class="mhp-block">
      <h3 class="block-title">
        Post log <span class="block-sub">newest first · {totalPosts} entries across {log.length} days</span>
      </h3>
      <ol class="log">
        {#each log as day}
          <li class="log-day">
            <div class="log-date">
              <span class="ld-iso">{day.date}</span>
              <span class="ld-ago">{ago(day.daysAgo)}</span>
              <span class="ld-n">{day.entries.length} post{day.entries.length === 1 ? "" : "s"}</span>
            </div>
            <ul class="log-entries">
              {#each day.entries as e}
                <li class="log-row" class:manual={e.source === "manual"}>
                  <span class="src src-{e.source}">{e.source === "manual" ? "manual" : "auto"}</span>
                  <span class="plat"
                    >{e.platform}{#if e.subreddit}<span class="sub">&nbsp;r/{e.subreddit}</span
                      >{/if}</span
                  >
                  <span class="note">{e.note ?? ""}</span>
                </li>
              {/each}
            </ul>
          </li>
        {/each}
      </ol>
    </div>
  {/if}
</section>

<style>
  .mhp {
    background: #0d1320;
    border: 1px solid var(--rule);
    border-radius: 8px;
    padding: 1.25rem 1.4rem 1.5rem;
    margin: 0 auto 1.5rem;
    max-width: 1100px;
    font-family: "Iowan Old Style", "Palatino Linotype", Georgia, serif;
    color: #cdd6e4;
  }
  .mhp-head h2 { margin: 0 0 0.35rem; color: var(--crimson); font-size: 1.1rem; letter-spacing: 0.02em; }
  .mhp-sub { margin: 0 0 0.6rem; font-size: 0.78rem; line-height: 1.5; color: #8b97a8; }
  .mhp-sub code { color: var(--crimson); background: var(--rule); padding: 0.05rem 0.3rem; border-radius: 3px; overflow-wrap: anywhere; }
  .mhp-stats { display: flex; flex-wrap: wrap; gap: 0.4rem 0.9rem; font-size: 0.75rem; color: #9aa6b6; }
  .mhp-stats strong { color: #e2e8f0; font-weight: 700; }
  .mhp-stats .muted { color: #6f7c8d; }
  .mhp-msg { font-size: 0.78rem; color: #8b97a8; }

  .mhp-block { margin-top: 1.4rem; }
  .block-title { font-size: 0.82rem; color: #7dd3fc; margin: 0 0 0.5rem; letter-spacing: 0.03em; }
  .block-sub { color: #6f7c8d; font-size: 0.7rem; font-weight: normal; letter-spacing: 0; }

  .chart-wrap { width: 100%; overflow: hidden; }
  .mhp-svg { width: 100%; height: auto; display: block; }

  .legend { display: flex; flex-wrap: wrap; gap: 0.35rem 1rem; font-size: 0.68rem; color: #9aa6b6; margin-top: 0.35rem; }
  .legend-item { display: inline-flex; align-items: center; gap: 0.35rem; }
  .dot { width: 8px; height: 8px; border-radius: 2px; flex: none; }

  .chan-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.3rem; }
  .chan-row {
    display: grid;
    grid-template-columns: 5.5rem minmax(0, 1fr) 2rem minmax(0, 11rem);
    align-items: center;
    gap: 0.6rem;
    background: #0f1626;
    border: 1px solid rgba(255, 255, 255, 0.05);
    border-radius: 5px;
    padding: 0.4rem 0.6rem;
    font-size: 0.74rem;
  }
  .chan-row.stale { border-color: rgba(251, 146, 60, 0.28); }
  .chan-name { color: #e2e8f0; overflow-wrap: anywhere; }
  .chan-bar { display: flex; gap: 2px; height: 10px; min-width: 0; }
  .chan-bar .seg { border-radius: 2px; min-width: 3px; }
  .chan-n { color: #cdd6e4; text-align: right; }
  .chan-last { color: #8b97a8; font-size: 0.68rem; overflow-wrap: anywhere; }
  .chan-detail { color: #6f7c8d; font-style: italic; }

  .log { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.5rem; }
  .log-day { background: #0f1626; border: 1px solid rgba(255, 255, 255, 0.05); border-radius: 5px; padding: 0.45rem 0.6rem; }
  .log-date { display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.5rem; margin-bottom: 0.3rem; }
  .ld-iso { color: var(--crimson); font-size: 0.76rem; }
  .ld-ago, .ld-n { color: #6f7c8d; font-size: 0.65rem; }
  .log-entries { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.2rem; }
  .log-row { display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.45rem; font-size: 0.72rem; }
  .src { font-size: 0.58rem; padding: 0.06rem 0.38rem; border-radius: 999px; flex: none; text-transform: uppercase; letter-spacing: 0.04em; }
  .src-postiz { background: rgba(167, 139, 250, 0.16); color: #c4b5fd; }
  .src-manual { background: rgba(251, 146, 60, 0.16); color: #fdba74; }
  .plat { color: #e2e8f0; }
  .sub { color: #7dd3fc; }
  .note { color: #8b97a8; font-style: italic; flex: 1; min-width: 8rem; overflow-wrap: anywhere; }

  @media (max-width: 640px) {
    .mhp { padding: 1rem 0.85rem 1.2rem; }
    .chan-row { grid-template-columns: 4.5rem minmax(0, 1fr) 1.8rem; row-gap: 0.25rem; }
    .chan-last { grid-column: 1 / -1; }
  }
</style>
